package cn.itcast.bos.domain.auth;
// Generated 2017-3-15 10:47:31 by Hibernate Tools 3.2.2.GA


import cn.itcast.bos.domain.user.User;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="T_AUTH_ROLE"
    ,schema="BOS44"
    , uniqueConstraints = @UniqueConstraint(columnNames="NAME") 
)
public class Role  implements java.io.Serializable {


     private String id;
     private String name;
     private String code;
     private String description;
     private Set<Function> functions = new HashSet<Function>(0);
     //角色关联用户：单向关联
     private Set<User> users = new HashSet<User>(0);

    public Role() {
    }

    public Role(String name, String code, String description, Set<Function> functions, Set<User> users) {
       this.name = name;
       this.code = code;
       this.description = description;
       this.functions = functions;
       this.users = users;
    }
   
     @GenericGenerator(name="generator", strategy="uuid")@Id @GeneratedValue(generator="generator")
    
    @Column(name="ID", unique=true, nullable=false, length=32)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="NAME", unique=true)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="CODE")
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="T_AUTH_ROLE_FUNCTION", schema="BOS44", joinColumns = { 
        @JoinColumn(name="ROLE_ID", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="FUNCTION_ID", nullable=false, updatable=false) })
    public Set<Function> getFunctions() {
        return this.functions;
    }
    
    public void setFunctions(Set<Function> functions) {
        this.functions = functions;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="T_AUTH_USER_ROLE", schema="BOS44", joinColumns = { 
        @JoinColumn(name="ROLE_ID", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="USER_ID", nullable=false, updatable=false) })
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


